# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823ca71d8301105b093c24c2fbaf002302851282162c7d53b48f0560142ac5dd90539a56052a142601c44176e6023fe2ae6fb6094e34ba69e8c6cd85075e20cf

test:
  secret_key_base: cdf3f213110fe546168c14e7d66a9361ee1bec00a303d100c150127811fc9b8abade09bebc011cb019553db29aa60eaed3cfed7277e7597d488a8bb681b839f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
